### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by ihgumilar** [timeflux/timeflux_brainflow#2]
Do you have manual how to start this ?

**Comment by mesca** [comment]
You can start with the general Timeflux [tutorial](https://doc.timeflux.io/en/stable/usage/hello_world.html). Once you get the basics, have a look at the Brainflow [examples](https://github.com/timeflux/timeflux_brainflow/tree/master/examples). If you still need some help, join us on our [Slack channel](https://timeflux.io/slack)!

**Comment by ihgumilar** [comment]
Thanks a lot. I will try to explore this. I have no knowledge about YMAL language :)
